### ISSUE TITLE
reactjs with redux oidc client

### ISSUE THREAD

**Issue by Hyjaz** [maxmantz/redux-oidc-example#11]
Hello,

I was able to setup the oidc client, with your redux-oidc library.

What I am having trouble with right now, is basically authorizing the access_token when the user makes a request to my backend api that is made with asp.net. 

I just have a hard time understanding which namespace to use in order to validate the bearer token.

Would you have a sample with asp.net Core 2.0, that uses azure ad, and reactjs as the client?

This is a question.

**Comment by maxmantz** [comment]
Sorry, but this would be out of scope of this project. Normally, the correct OWIN middleware setup makes sure that the token is handled correctly. Have a look at [IdentityServer4](https://github.com/IdentityServer/IdentityServer4) for help on backend token validation for OIDC. It has been made by the same guys who made oidc-client-js. I'm sure they can help you out :)
