### ISSUE TITLE
How would I use this with redux

### ISSUE THREAD

**Issue by Hyjaz** [maxmantz/redux-oidc-example#12]
Hi, 
How would I use this with redux and not redux-saga. I get a null value for user.

It is very frustrating.

**Comment by jonaskello** [comment]
I would tend to agree that the use of redux-saga for this example is overkill and makes the threshold higher for new users as they need to learn yet another library. (Don't get me wrong, I use redux-saga myself and it's great for some cases).

I could make a PR to remove redux-saga from the example if that is something that would be accepted?

**Comment by jonaskello** [comment]
@Hyjaz Have a look at the [refactor branch](https://github.com/jonaskello/redux-oidc-example/tree/refactor) of my fork, it has no redux-saga in it.

**Comment by Hyjaz** [comment]
@jonaskello I'm good with your changes. I have left a few trivial comments. We made this work after a few days.
