### ISSUE TITLE
Missing File?

### ISSUE THREAD

**Issue by zerounix** [maxmantz/redux-oidc-example#16]
Hi,

i'm trying out your example and there seems to be a missing file?
https://github.com/maxmantz/redux-oidc-example/blob/master/src/storeWithoutSilentRenew.js
Line 6
import { loadSubscriptionsSaga } from './sagas';

Is this file missing or am I missing something here?

**Comment by maxmantz** [comment]
Hi,

that's true. The file you've linked is the example on how to use this library when you don't have silent renew set up. It is only there for legacy purposes. This file was overlooked during the recent refactoring when the dependency on redux-saga was removed. You can safely ignore that file and any reference to sagas overall. I will clean this up shortly.

**Comment by zerounix** [comment]
Ok, thanks!
