### ISSUE TITLE
open any link in new tab on same browser ,i can't get user Data

### ISSUE THREAD

**Issue by sanjaykumarpushadapu** [maxmantz/redux-oidc-example#20]

**Comment by maxmantz** [comment]
This is very little information to go on, but making an educated guess, this probably has to do with the userManager settings. User information is stored in `sessionStorage` by default, but can be switched to `localStorage`. If set to `localStorage`, existing user information is used when opening a new tab.

**Comment by sanjaykumarpushadapu** [comment]
Thank you ,how can be switched to localStorage?

**Comment by maxmantz** [comment]
Please refer to the [oidc-client wiki](https://github.com/IdentityModel/oidc-client-js/wiki) for configuration options.

**Comment by sanjaykumarpushadapu** [comment]
Thank you
