### ISSUE TITLE
Dynamically load the UserManagerSettings

### ISSUE THREAD

**Issue by wdspider** [maxmantz/redux-oidc-example#21]
Hi,

I'm having trouble modifying the sample code so that it dynamically loads the UserManagerSettings out of an appconfig.json file located in the public folder of a create-react-app project. Would it be possible for you provide a sample on how to do this? My UserManagerSettings vary with each deployment and thus cannot be set at compile time.

Thanks.

**Comment by maxmantz** [comment]
No, that would be beyond the scope of this project. Please refer to the create-react-app documentation or ask for help there on how to dynamically load parameters.
