### ISSUE TITLE
Page not available when running example.

### ISSUE THREAD

**Issue by Sotorin** [maxmantz/redux-oidc-example#3]
Hi,
I'm having problems running your example. I followed all the instructions (npm install, node server) [installed immutable too]. Server seems to be running (had to change the port [rethinkdb was running on 8080 on my machine]) 
<img width="737" alt="screen shot 2016-11-22 at 5 40 19 pm" src="https://cloud.githubusercontent.com/assets/1545379/20546516/3cf53862-b0db-11e6-8e29-1b4ad6c08da5.png">

I keep getting this:
<img width="715" alt="screen shot 2016-11-22 at 5 44 39 pm" src="https://cloud.githubusercontent.com/assets/1545379/20546554/7455c484-b0db-11e6-8290-20b8e42debb3.png">

There was another user who created a fork of your example to integrate redux-auth-wrapper and I'm also having problems running his example as well. Identical one as a matter of fact.

**Comment by maxmantz** [comment]
The server runs on TLS so you need to open https://localhost:8000 for it to work.

**Comment by Sotorin** [comment]
Outstanding:)... This worked !

**Comment by malachib** [comment]
Can we please have this reflected in the readme?  Anything auth should be secured, obviously, but for nubs like me it would help a lot!

**Comment by maxmantz** [comment]
I've edited the readme to reflect this.
