### ISSUE TITLE
Is it good way to share store across app solution?

### ISSUE THREAD

**Issue by Jenan** [maxmantz/redux-oidc-example#6]
Here redux-oidc-example/src/utils/request.js is example how get the access token from redux store and the redux store is shared in import:

Is it good way to do this? Could be better pass the access token like a parameter and connect the oidc key into component?

Thanks for your opinion. :)

```js
import store from '../store';

// a request helper which reads the access_token from the redux state and passes it in its HTTP request
export default function apiRequest(url, method = 'GET') {
  const token = store.getState().oidc.user.access_token;
  const headers = new Headers();
  headers.append('Accept', 'application/json');
  headers.append('Authorization', `Bearer ${token}`);

  const options = {
    method,
    headers
  };

  return fetch(url, options)
    .then((res) => res.json())
    .then((data) => ({data}))
    .catch((error) => ({ error }));
}
```
Token pass as paramater:
```js
// a request helper which reads the access_token from the redux state and passes it in its HTTP request
export default function apiRequest(url, method = 'GET', token) {
  const headers = new Headers();
  headers.append('Accept', 'application/json');
  headers.append('Authorization', `Bearer ${token}`);

  const options = {
    method,
    headers
  };

  return fetch(url, options)
    .then((res) => res.json())
    .then((data) => ({data}))
    .catch((error) => ({ error }));
}
```
And in component use connect method with:

```js
function mapStateToProps(state) {
  return {
    token: oidc.user.access_token
  };
}
```
Pass the access token from component into action creator and call the api with this paramater.

**Comment by maxmantz** [comment]
sure, your idea would also work just fine.

**Comment by Jenan** [comment]
@maxmantz  I have a question about JWT - I've used the server rendering for react&redux app and I've wondered if is safe render JWT into html hidden field and read this token from hidden field? What do you think about rendering JWT into HTML hidden input?

**Comment by maxmantz** [comment]
Why do you want to do that?

**Comment by Jenan** [comment]
I have a JWT token store in cookie on the server and I want to use the redux and react rendered from server because it's faster in initial application start. If I want to render react-redux app from server the way for passing the data from server to the client it is pass like this:

```js
    <script type="text/javascript">

        window.__initialState__ =  @Html.Raw(JsonConvert.SerializeObject(Model, new JsonSerializerSettings
        {
                               NullValueHandling = NullValueHandling.Ignore
        }));

    </script>
```
```js
const store = createStore(combineReducers({
    app: commonReducer
}), (window as any).__initialState__ ,applyMiddleware(logger));
```

Render JWT into `window.__initialState__`  like this?

What do you think about it?

**Comment by maxmantz** [comment]
It seems a little complicated to me, but if it works for you, then sure, go ahead...

**Comment by Jenan** [comment]
OK, thanks for you time. Do you have some another contact where is possible to contact you about react-redux things? Thank you.

**Comment by maxmantz** [comment]
I'm happy to help with questions about the usage of this library. But please understand that I'm not a consultant and don't have the time and resources to answer questions beyond that.
